name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Jellyfin.Plugin.Chromecast/Jellyfin.Plugin.Chromecast.csproj

      - name: Build
        run: dotnet build Jellyfin.Plugin.Chromecast/Jellyfin.Plugin.Chromecast.csproj -c Release --no-restore
